config/routes.rb
Rails.application.routes.draw do
  
  get 'pages/dashboard'

  get 'pages/busqueda'

  get 'pages/opinion'
  
  get 'pages/recibidas'  

  get 'home/search_parking'

  get 'pages/search_parking'
  
  get 'pages/about_us'

  get 'pages/faq'

  get 'pages/contact_us'

  resources :availability_parking_places
  resources :day_of_weeks
  resources :payments
  resources :payment_document_types
  resources :feedbacks
  resources :favorites
  resources :bookings
  resources :booking_statuses
  resources :payment_types
  resources :parking_places
  resources :owner_types
  resources :parking_types
  resources :organization_members
  resources :member_types
  resources :organizations
  resources :profiles, only: [:edit, :update]
  resources :document_types
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  get 'home/index', to: 'home#index', as: 'home'
  

  root 'home#index' 

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :booking_status
  belongs_to :payment_type
  belongs_to :parking_place
  belongs_to :user
  
  validates :booking_date, presence: true
  validates :start_date, presence: true
  validates :finish_date, presence: true
  validates :vehicle_plate, presence: true
  validates :amount_payable, presence: true
  validates :payment_type_id, presence: true
  validates :parking_place_id, presence: true
  validates :user_id, presence: true
end

app/models/booking_status.rb
class BookingStatus < ActiveRecord::Base
end

app/models/day_of_week.rb
class DayOfWeek < ActiveRecord::Base
end

app/models/document_type.rb
class DocumentType < ActiveRecord::Base
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :parking_place
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :booking
end

app/models/member_type.rb
class MemberType < ActiveRecord::Base
end

app/models/organization.rb
class Organization < ActiveRecord::Base
    belongs_to :user
   # belongs_to :profile
    has_many :organization_member 
    
    validates :name, presence: true
    validates :ruc, presence: true
    validates :address, presence: true
    validates :user, presence: true
 
 
end

app/models/owner_type.rb
class OwnerType < ActiveRecord::Base
end

app/models/parking_place.rb
class ParkingPlace < ActiveRecord::Base
  belongs_to :parking_type
  belongs_to :owner_type
  belongs_to :organization
  belongs_to :user
  has_many :bookings
  validates :description, presence: true
  validates :spaces_number, presence: true
  validates :address, presence: true
  validates :organization, presence: true
  validates :owner_type, presence: true
  validates :parking_type, presence: true
  validates :user, presence: true
  
  geocoded_by :address, :latitude  => :georeference_x, :longitude => :georeference_y # ActiveRecord
  after_validation :geocode
  has_many   :bookings
end

app/models/parking_type.rb
class ParkingType < ActiveRecord::Base
  has_many :parking_place
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :payment_type
  belongs_to :payment_document
  belongs_to :booking
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base
    has_many :bookings
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :document_type
  belongs_to :user
  
  # has_attached_file :photo, styles: { thumb: '100x100>', medium: '300x300>'},    
  #   default_url: '/images/:style/missing.png'  
  # validates_attachment :photo,    
  #   content_type: { content_type: ['image/jpeg', 'image/png', 'image/gif'] }  

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  validates_attachment :photo,
    :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] }

#  validates :first_name, presence: true
#  validates :last_name, presence: true
#  validates :document_type, presence: true
#  validates :document_number, presence: true

  def full_name
      self.first_name + " " + self.last_name
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_one :profile
  has_many :organization
  
  enum role: [:user, :operator, :chef, :admin]

  after_initialize :set_default_role
  after_create :set_default_profile

  def set_default_role
    self.role ||= :user
  end

  def set_default_profile
    profile = Profile.new
    profile.user = self
    profile.save
  end

  def name
    friendly_name
  end

  def friendly_name
    self.profile.first_name.nil? ? self.email : self.profile.full_name
  end

  def name_full
      self.profile.full_name
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def search_parking
  end
  
  def index
     
     @q = ParkingPlace.ransack(params[:q])
     @parks = @q.result
  
    #Lista de los parques no reservados
    ids = Booking.all.map(&:parking_place_id).to_a
    
     @park =   @parks.where.not(id: ids)
     
     
     #@park =  ParkingPlace.all
  end
  
  def search_parking
   
     
     @q = ParkingPlace.ransack(params[:q])
     @parks = @q.result
  
    #Lista de los parques no reservados
    ids = Booking.all.map(&:parking_place_id).to_a
    
     @park =   @parks.where.not(id: ids)
     
     
     #@park =  ParkingPlace.all
  
  end
  
  def search
      
      @parking_places = ParkingPlace.search(params[:search_text]).result
      if @parking_places
          @current_mode = 'results'
      else
          @current_mode = 'default'
      end  
      
  end
  
  def filter 
   
     respond_to do |format|
       format.html{redirect_to action: :index}
     end
    
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/home/_tabla.html.erb
<%- model_class = ParkingPlace -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:Codigo) %></th>
      <th><%= model_class.human_attribute_name(:Descripcion) %></th>
      <th><%= model_class.human_attribute_name(:Tarifa_por_hora) %></th>
      <th><%= model_class.human_attribute_name(:Numero_espacios) %></th>
      <th><%= model_class.human_attribute_name(:Direccion) %></th>
      <th><%= model_class.human_attribute_name(:Tipo_de_estacionamiento) %></th>
      <th><%= model_class.human_attribute_name(:Organizacion) %></th>
      
      <th><%=t '.actions', :default => t("helpers.Acciones") %></th>
    </tr>
  </thead>
  <tbody>
    <% @parking_places.each do |parking_place| %>
      <tr>
        <td><%= link_to parking_place.id, parking_place_path(parking_place) %></td>
        <td><%= parking_place.description %></td>
        <td><%= parking_place.hourly_rate %></td>
        <td><%= parking_place.spaces_number %></td>
        <td><%= parking_place.address %></td>
        <td><%= parking_place.parking_type_id %></td>
        <td><%= parking_place.organization_id %></td>
        
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_parking_place_path(parking_place), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      parking_place_path(parking_place),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<!--%= search_form_for @q, url: home_path do |f| %-->


  
  <!--%= f.label :description_cont %-->
  <!--%= f.search_field :description_cont %-->

  <!--%= f.submit %-->
<!--% end %-->

        <!--%for park in @park%-->
        
        <!--%=park.description%-->
        <!--%=park.address%-->
        <!--%=park.parking_type_id%-->
        <!--%=park.organization_id%-->
        
        <!--%end%>
        
<!--% if @parking_places %-->
  <!--%= render 'tabla' %-->
<!--% end %--> 

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->

  <ol class="carousel-indicators">

    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>

  </ol>

  <!-- Wrapper for slides -->

  <div class="carousel-inner" role="listbox">

    <div class="item active">

      <%= image_tag "auto1.jpg", html: { alt: "auto1" } %>

      <div class="carousel-caption">

        <h3>Bienvenido</h3>
        
       
        <p></p>

      </div>

    </div>

    <div class="item">

      <%= image_tag "auto2.jpg", html: { alt: "auto2" } %>

      <div class="carousel-caption">

        <h3>Bienvenido</h3>

        <p></p>

      </div>

    </div>

    <div class="item">

      <%= image_tag "auto3.jpg", html: { alt: "auto3" }%>

      <div class="carousel-caption">

        <h3>Bienvenido</h3>

        <p></p>

      </div>

    </div>

  </div>

  <!-- Controls -->

  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">

    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>

    <span class="sr-only">Previous</span>

  </a>

  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">

    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>

    <span class="sr-only">Next</span>

  </a>

</div>

app/views/home/search_parking.html.erb
<%= search_form_for @q, url: home_path do |f| %>

  
  <%= f.label :description_cont %>
  <%= f.search_field :description_cont %>

  <%= f.submit %>
<% end %>

        <%for park in @park%>
        <%=park.description%>
        <%=park.address%>
        <%=park.parking_type.name%>
        <%=park.organization.name%>
        
        <%end%>
<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>
<script type=text/javascript>
  handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

<% if @parking_places %>
  <%= render 'tabla' %>
<% end %>  