config/routes.rb
Rails.application.routes.draw do
  
  get 'pages/dashboard'

  get 'pages/busqueda'

  get 'pages/opinion'
  
  get 'pages/recibidas'  

  get 'home/search_parking'

  get 'pages/search_parking'
  
  get 'pages/about_us'

  get 'pages/faq'

  get 'pages/contact_us'

  resources :availability_parking_places
  resources :day_of_weeks
  resources :payments
  resources :payment_document_types
  resources :feedbacks
  resources :favorites
  resources :bookings
  resources :booking_statuses
  resources :payment_types
  resources :parking_places
  resources :owner_types
  resources :parking_types
  resources :organization_members
  resources :member_types
  resources :organizations
  resources :profiles, only: [:edit, :update]
  resources :document_types
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  get 'home/index', to: 'home#index', as: 'home'
  

  root 'home#index' 

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :booking_status
  belongs_to :payment_type
  belongs_to :parking_place
  belongs_to :user
  
  validates :booking_date, presence: true
  validates :start_date, presence: true
  validates :finish_date, presence: true
  validates :vehicle_plate, presence: true
  validates :amount_payable, presence: true
  validates :payment_type_id, presence: true
  validates :parking_place_id, presence: true
  validates :user_id, presence: true
end

app/models/booking_status.rb
class BookingStatus < ActiveRecord::Base
end

app/models/day_of_week.rb
class DayOfWeek < ActiveRecord::Base
end

app/models/document_type.rb
class DocumentType < ActiveRecord::Base
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :parking_place
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :booking
end

app/models/member_type.rb
class MemberType < ActiveRecord::Base
end

app/models/organization.rb
class Organization < ActiveRecord::Base
    belongs_to :user
   # belongs_to :profile
    has_many :organization_member 
    
    validates :name, presence: true
    validates :ruc, presence: true
    validates :address, presence: true
    validates :user, presence: true
 
 
end

app/models/owner_type.rb
class OwnerType < ActiveRecord::Base
end

app/models/parking_place.rb
class ParkingPlace < ActiveRecord::Base
  belongs_to :parking_type
  belongs_to :owner_type
  belongs_to :organization
  belongs_to :user
  has_many :bookings
  validates :description, presence: true
  validates :spaces_number, presence: true
  validates :address, presence: true
  validates :organization, presence: true
  validates :owner_type, presence: true
  validates :parking_type, presence: true
  validates :user, presence: true
  
  geocoded_by :address, :latitude  => :georeference_x, :longitude => :georeference_y # ActiveRecord
  after_validation :geocode
  has_many   :bookings
end

app/models/parking_type.rb
class ParkingType < ActiveRecord::Base
  has_many :parking_place
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :payment_type
  belongs_to :payment_document
  belongs_to :booking
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base
    has_many :bookings
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :document_type
  belongs_to :user
  
  # has_attached_file :photo, styles: { thumb: '100x100>', medium: '300x300>'},    
  #   default_url: '/images/:style/missing.png'  
  # validates_attachment :photo,    
  #   content_type: { content_type: ['image/jpeg', 'image/png', 'image/gif'] }  

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  validates_attachment :photo,
    :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] }

#  validates :first_name, presence: true
#  validates :last_name, presence: true
#  validates :document_type, presence: true
#  validates :document_number, presence: true

  def full_name
      self.first_name + " " + self.last_name
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_one :profile
  has_many :organization
  
  enum role: [:user, :operator, :chef, :admin]

  after_initialize :set_default_role
  after_create :set_default_profile

  def set_default_role
    self.role ||= :user
  end

  def set_default_profile
    profile = Profile.new
    profile.user = self
    profile.save
  end

  def name
    friendly_name
  end

  def friendly_name
    self.profile.first_name.nil? ? self.email : self.profile.full_name
  end

  def name_full
      self.profile.full_name
  end
  
end

app/controllers/booking_statuses_controller.rb
class BookingStatusesController < ApplicationController
  before_action :set_booking_status, only: [:show, :edit, :update, :destroy]

  # GET /booking_statuses
  # GET /booking_statuses.json
  def index
    @booking_statuses = BookingStatus.all
  end

  # GET /booking_statuses/1
  # GET /booking_statuses/1.json
  def show
  end

  # GET /booking_statuses/new
  def new
    @booking_status = BookingStatus.new
  end

  # GET /booking_statuses/1/edit
  def edit
  end

  # POST /booking_statuses
  # POST /booking_statuses.json
  def create
    @booking_status = BookingStatus.new(booking_status_params)

    respond_to do |format|
      if @booking_status.save
        format.html { redirect_to @booking_status, notice: 'Booking status was successfully created.' }
        format.json { render :show, status: :created, location: @booking_status }
      else
        format.html { render :new }
        format.json { render json: @booking_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /booking_statuses/1
  # PATCH/PUT /booking_statuses/1.json
  def update
    respond_to do |format|
      if @booking_status.update(booking_status_params)
        format.html { redirect_to @booking_status, notice: 'Booking status was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking_status }
      else
        format.html { render :edit }
        format.json { render json: @booking_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /booking_statuses/1
  # DELETE /booking_statuses/1.json
  def destroy
    @booking_status.destroy
    respond_to do |format|
      format.html { redirect_to booking_statuses_url, notice: 'Booking status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking_status
      @booking_status = BookingStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_status_params
      params.require(:booking_status).permit(:name, :description)
    end
end

app/helpers/booking_statuses_helper.rb
module BookingStatusesHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/booking_statuses/_form.html.erb
<%= simple_form_for @booking_status, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= error_span(@booking_status[:name]) %>
  <%= f.input :description %>
  <%= error_span(@booking_status[:description]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                booking_statuses_path, :class => 'btn btn-default' %>
<% end %>

app/views/booking_statuses/edit.html.erb
<%- model_class = BookingStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/booking_statuses/index.html.erb
<%- model_class = BookingStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @booking_statuses.each do |booking_status| %>
      <tr>
        <td><%= link_to booking_status.id, booking_status_path(booking_status) %></td>
        <td><%= booking_status.name %></td>
        <td><%= booking_status.description %></td>
        <td><%=l booking_status.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_booking_status_path(booking_status), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      booking_status_path(booking_status),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_booking_status_path,
            :class => 'btn btn-primary' %>

app/views/booking_statuses/new.html.erb
<%- model_class = BookingStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/booking_statuses/show.html.erb
<%- model_class = BookingStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @booking_status.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @booking_status.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              booking_statuses_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_booking_status_path(@booking_status), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              booking_status_path(@booking_status),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>