config/routes.rb
Rails.application.routes.draw do
  
  get 'pages/dashboard'

  get 'pages/busqueda'

  get 'pages/opinion'
  
  get 'pages/recibidas'  

  get 'home/search_parking'

  get 'pages/search_parking'
  
  get 'pages/about_us'

  get 'pages/faq'

  get 'pages/contact_us'

  resources :availability_parking_places
  resources :day_of_weeks
  resources :payments
  resources :payment_document_types
  resources :feedbacks
  resources :favorites
  resources :bookings
  resources :booking_statuses
  resources :payment_types
  resources :parking_places
  resources :owner_types
  resources :parking_types
  resources :organization_members
  resources :member_types
  resources :organizations
  resources :profiles, only: [:edit, :update]
  resources :document_types
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  get 'home/index', to: 'home#index', as: 'home'
  

  root 'home#index' 

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :booking_status
  belongs_to :payment_type
  belongs_to :parking_place
  belongs_to :user
  
  validates :booking_date, presence: true
  validates :start_date, presence: true
  validates :finish_date, presence: true
  validates :vehicle_plate, presence: true
  validates :amount_payable, presence: true
  validates :payment_type_id, presence: true
  validates :parking_place_id, presence: true
  validates :user_id, presence: true
end

app/models/booking_status.rb
class BookingStatus < ActiveRecord::Base
end

app/models/day_of_week.rb
class DayOfWeek < ActiveRecord::Base
end

app/models/document_type.rb
class DocumentType < ActiveRecord::Base
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :parking_place
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :booking
end

app/models/member_type.rb
class MemberType < ActiveRecord::Base
end

app/models/organization.rb
class Organization < ActiveRecord::Base
    belongs_to :user
   # belongs_to :profile
    has_many :organization_member 
    
    validates :name, presence: true
    validates :ruc, presence: true
    validates :address, presence: true
    validates :user, presence: true
 
 
end

app/models/owner_type.rb
class OwnerType < ActiveRecord::Base
end

app/models/parking_place.rb
class ParkingPlace < ActiveRecord::Base
  belongs_to :parking_type
  belongs_to :owner_type
  belongs_to :organization
  belongs_to :user
  has_many :bookings
  validates :description, presence: true
  validates :spaces_number, presence: true
  validates :address, presence: true
  validates :organization, presence: true
  validates :owner_type, presence: true
  validates :parking_type, presence: true
  validates :user, presence: true
  
  geocoded_by :address, :latitude  => :georeference_x, :longitude => :georeference_y # ActiveRecord
  after_validation :geocode
  has_many   :bookings
end

app/models/parking_type.rb
class ParkingType < ActiveRecord::Base
  has_many :parking_place
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :payment_type
  belongs_to :payment_document
  belongs_to :booking
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base
    has_many :bookings
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :document_type
  belongs_to :user
  
  # has_attached_file :photo, styles: { thumb: '100x100>', medium: '300x300>'},    
  #   default_url: '/images/:style/missing.png'  
  # validates_attachment :photo,    
  #   content_type: { content_type: ['image/jpeg', 'image/png', 'image/gif'] }  

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  validates_attachment :photo,
    :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] }

#  validates :first_name, presence: true
#  validates :last_name, presence: true
#  validates :document_type, presence: true
#  validates :document_number, presence: true

  def full_name
      self.first_name + " " + self.last_name
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_one :profile
  has_many :organization
  
  enum role: [:user, :operator, :chef, :admin]

  after_initialize :set_default_role
  after_create :set_default_profile

  def set_default_role
    self.role ||= :user
  end

  def set_default_profile
    profile = Profile.new
    profile.user = self
    profile.save
  end

  def name
    friendly_name
  end

  def friendly_name
    self.profile.first_name.nil? ? self.email : self.profile.full_name
  end

  def name_full
      self.profile.full_name
  end
  
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:payment_date, :start_date, :finish_date, :payment_type_id, :amount_paid, :payment_document_id, :document_number, :booking_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/payments/_form.html.erb
<%= simple_form_for @payment, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :payment_date %>
  <%= error_span(@payment[:payment_date]) %>
  <%= f.input :start_date %>
  <%= error_span(@payment[:start_date]) %>
  <%= f.input :finish_date %>
  <%= error_span(@payment[:finish_date]) %>
  <%= f.input :payment_type_id %>
  <%= error_span(@payment[:payment_type_id]) %>
  <%= f.input :amount_paid %>
  <%= error_span(@payment[:amount_paid]) %>
  <%= f.input :payment_document_type_id %>
  <%= error_span(@payment[:payment_document_type_id]) %>
  <%= f.input :document_number %>
  <%= error_span(@payment[:document_number]) %>
  <%= f.input :booking_id %>
  <%= error_span(@payment[:booking_id]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                payments_path, :class => 'btn btn-default' %>
<% end %>

app/views/payments/edit.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/payments/index.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:payment_date) %></th>
      <th><%= model_class.human_attribute_name(:start_date) %></th>
      <th><%= model_class.human_attribute_name(:finish_date) %></th>
      <th><%= model_class.human_attribute_name(:payment_type_id) %></th>
      <th><%= model_class.human_attribute_name(:amount_paid) %></th>
      <th><%= model_class.human_attribute_name(:payment_document_type_id) %></th>
      <th><%= model_class.human_attribute_name(:document_number) %></th>
      <th><%= model_class.human_attribute_name(:booking_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= link_to payment.id, payment_path(payment) %></td>
        <td><%= payment.payment_date %></td>
        <td><%= payment.start_date %></td>
        <td><%= payment.finish_date %></td>
        <td><%= payment.payment_type_id %></td>
        <td><%= payment.amount_paid %></td>
        <td><%= payment.payment_document_type_id %></td>
        <td><%= payment.document_number %></td>
        <td><%= payment.booking_id %></td>
        <td><%=l payment.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_payment_path(payment), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      payment_path(payment),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_payment_path,
            :class => 'btn btn-primary' %>

app/views/payments/new.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/payments/show.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:payment_date) %>:</strong></dt>
  <dd><%= @payment.payment_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_date) %>:</strong></dt>
  <dd><%= @payment.start_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:finish_date) %>:</strong></dt>
  <dd><%= @payment.finish_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:payment_type_id) %>:</strong></dt>
  <dd><%= @payment.payment_type_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amount_paid) %>:</strong></dt>
  <dd><%= @payment.amount_paid %></dd>
  <dt><strong><%= model_class.human_attribute_name(:payment_document_type_id) %>:</strong></dt>
  <dd><%= @payment.payment_document_type_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:document_number) %>:</strong></dt>
  <dd><%= @payment.document_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:booking_id) %>:</strong></dt>
  <dd><%= @payment.booking_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              payments_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_payment_path(@payment), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              payment_path(@payment),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>